version: '2'
services:
  nginx:
    image: registry.jincor.com/frontend/landings-production:latest
    build:
      context: ./
      dockerfile: landings.Dockerfile
    environment:
      API_HOST: "http://172.104.143.86:8080"
    ports:
      - 443:443
      - 80:80

  laughing-robot:
    image: registry.jincor.com/frontend/laughing-robot-production:latest
    ports:
      - 3000