version: '2'
services:
  nginx:
    image: registry.jincor.com/frontend/landings-production:latest
    volumes:
      - /root/projects/frontend/frontend-landing-ico/dist:/var/apps/ico
      - /root/projects/frontend/frontend-landing/dist:/var/apps/landing
    environment:
      API_HOST: "http://172.104.143.86:8080"
    ports:
      - 443:443
      - 80:80